In [3]:
import cv2

# Images

In [2]:
img = cv2.imread('./pic.jpg')

In [3]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 83  55  54]
  [ 83  55  54]
  [ 83  55  54]
  ...
  [ 76  50  50]
  [ 78  50  50]
  [ 78  50  50]]

 [[ 56  35  33]
  [ 56  35  33]
  [ 56  35  33]
  ...
  [ 51  30  29]
  [ 53  29  29]
  [ 53  29  29]]

 [[ 23   4   1]
  [ 23   4   1]
  [ 23   4   1]
  ...
  [ 25   5   4]
  [ 26   5   4]
  [ 26   5   4]]]


In [12]:
cv2.imshow("original",img)
cv2.waitKey(3000)  # it takes the time for which images hould be on screen , if we give 0 or does not give anything then it will be on screen till the time till we dont click on cross
cv2.destroyAllWindows()

In [5]:
img = cv2.resize(img,(200,200)) # (width,height)

In [6]:
bw_img = cv2.imread("./pic.jpg",0)  # it will generate graysacle image

In [26]:
bw_img = cv2.flip(bw_img,0)     # 0 -> rotate 90 , 1-> rotate 180 , -1 -> rotate 270
cv2.imshow("bw_original",bw_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [20]:
cv2.imshow("original",img)
k = cv2.waitKey()       
if k == ord("s"):       # if user press 's' then save it
    cv2.imwrite(r"C:\Users\tusha\Desktop\Computer vision\output.jpg",img)   # function for saving image
    cv2.destroyAllWindows()
else:
    cv2.destroyAllWindows()

# Videos

In [13]:
cap = cv2.VideoCapture("./video.mp4")
print(cap)
while True:
    ret,frame = cap.read()  # cap gives two variables one is binary which we have stored in ret and another is image which we have stored in frame
    frame = cv2.resize(frame,(700,250))
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)   # convert video to grayscale
    cv2.imshow("frame",gray)
    k = cv2.waitKey(25)     # more value of waitkey will slow the frame speed (25 is normal playback)
    if k == ord("q"):
        break
cap.release()
cv2.destroyAllWindows()

< cv2.VideoCapture 000001FA48EFE5D0>


### using webcam and saving video

In [19]:
cap = cv2.VideoCapture(0)  # pass 0 to access webcam
fourcc = cv2.VideoWriter_fourcc(*"XVID")    # it tells the video format
output = cv2.VideoWriter("output.avi",fourcc,20.0,(1000,700))   # it saves video (filename,format,fps,framesize)
while True:
    ret,frame = cap.read()  
    frame = cv2.resize(frame,(1000,700))
    cv2.imshow("frame",frame)
    output.write(frame)
    k = cv2.waitKey(25)    
    if k == ord("q"):
        break
cap.release()
output.release()
cv2.destroyAllWindows()

### using mobile

In [20]:
camera = "http://192.168.29.53:8080/video"
cap = cv2.VideoCapture(0)
cap.open(camera)
fourcc = cv2.VideoWriter_fourcc(*"XVID")
output = cv2.VideoWriter("output_mobile.avi",fourcc,20.0,(1000,700))
while True:
    ret,frame = cap.read()  
    frame = cv2.resize(frame,(1000,700))
    cv2.imshow("frame",frame)
    output.write(frame)
    k = cv2.waitKey(5)    
    if k == ord("q"):
        break
cap.release()
output.release()
cv2.destroyAllWindows()

### capturing online videos

In [ ]:
import pafy
url = "https://www.youtube.com/watch?v=wIAs97ynODo&list=PLaHodugB5x-Ddy_H951h0VHjOjfzZNCBh&index=7"
cap = cv2.VideoCapture(0)
data = pafy.new(url)
data = data.getbest(preftype="mp4")
cap.open(data.url)
fourcc = cv2.VideoWriter_fourcc(*"XVID")
output = cv2.VideoWriter("output_online.avi",fourcc,20.0,(1000,700))
while True:
    ret,frame = cap.read()  
    frame = cv2.resize(frame,(1000,700))
    cv2.imshow("frame",frame)
    output.write(frame)
    k = cv2.waitKey(5)    
    if k == ord("q"):
        break
cap.release()
output.release()
cv2.destroyAllWindows()

# Screen Recorder

In [27]:
!pip install pyautogui

     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 330.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 435.7 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 435.7 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.2 kB 435.7 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/61.2 kB 178.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/61.2 kB 187.0 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 171.7 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Installing build dependencies: start

In [28]:
import pyautogui as p
import numpy as np

rs = p.size()
fn = input("Please enter any file name and Path")
forcc = cv2.VideoWriter_fourcc(*'XVID')
output = cv2.VideoWriter(fn,fourcc,60.0,rs)

cv2.namedWindow('Live_Recording',cv2.WINDOW_NORMAL)
cv2.resizeWindow('Live_Recording',(600,400))

while True:
    img = p.screenshot()
    f = np.array(img)
    f = cv2.cvtColor(f,cv2.COLOR_BGR2RGB)
    output.write(f)
    cv2.imshow("Live_Recording",f)
    if cv2.waitKey(1) == ord('q'):
        break

output.release()
cv2.destroyAllWindows()

# Break video into multiple images and store in folder

In [31]:
videocap = cv2.VideoCapture('video.mp4')
ret,image = videocap.read()
count = 0 
while True:
    if ret == True:
        cv2.imwrite(r"C:\Users\tusha\Desktop\Computer vision\frames\imgN%d.jpg"%count,image)
        videocap.set(cv2.CAP_PROP_POS_MSEC,(count**100))    # it helps in taking screenshots after set time
        ret,image = videocap.read()
        cv2.imshow("res",image)
        count+=1
        if cv2.waitKey(1)== ord('q'):
            break
            cv2.destroyAllWindows()
videocap.release()
cv2.destroyAllWindows()

# Drawing function in opencv

### on image

In [57]:
img = np.zeros([512,512,3],np.uint8)*255 # black screen
img = np.ones([512,512,3],np.uint8)*255  # white screen
# img = cv2.imread('pic.jpg')
img = cv2.line(img,(0,0),(200,200),(154,92,424),8)  # (img,staring,ending,color{BGR},thickness)
img = cv2.arrowedLine(img,(0,125),(255,255),(255,0,0),10)
img = cv2.rectangle(img,(325,225),(510,328),(255,255,0),-1) # if we take thickness as -1 then it will fill the shape
img = cv2.circle(img,(425,525),25,(0,0,255),-1) # it will take radius instead of ending
img = cv2.putText(img,'Tushar gupta',(20,500),cv2.FONT_ITALIC,2,(1,125,225),5,cv2.LINE_AA) #(img,text,starting,font,fontsize,color,thickness,linetype)
cv2.imshow("res",img)
cv2.waitKey()
cv2.destroyAllWindows()

### on video

In [62]:
cap = cv2.VideoCapture(0)
while(cap.isOpened()):
    ret,frame = cap.read()
    font = cv2.FONT_HERSHEY_COMPLEX_SMALL
    frame = cv2.resize(frame,(1000,700))
    text = 'Height : '+ str(cap.get(4)) + ' Width : ' + str(cap.get(3))
    frame = cv2.putText(frame,text,(10,20),font,1,(0,0,0),1,cv2.LINE_AA)
    cv2.imshow('frame',frame)
    if cv2.waitKey(5)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

# Mouse callback functions

In [63]:
def draw(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        cv2.circle(img,(x,y),100,(125,0,125),5)
    if event == cv2.EVENT_RBUTTONDBLCLK:
        cv2.rectangle(img,(x,y),(x+100,y+75),(125,125,125),2)

cv2.namedWindow(winname='res')
img = np.zeros([512,512,3],np.uint8)*255
cv2.setMouseCallback("res",draw)
while True:
    cv2.imshow("res",img)
    if cv2.waitKey(1) == ord('q'):
        break
cv2.destroyAllWindows()

### to see cord and color on different click

In [82]:
def mouse_event(event,x,y,flag,param):
    font  = cv2.FONT_HERSHEY_COMPLEX
    if event == cv2.EVENT_LBUTTONDOWN:
        cord = ". " + str(x) + " , " + str(y)
        cv2.putText(img,cord,(x,y),font,1,(155,125,100),2)
    if event == cv2.EVENT_RBUTTONDOWN:
        b = img[y,x,0] # for blue channel is 0
        g = img[y,x,1] # for green channel is 1
        r = img[y,x,2] # for red channel is 2
        color_bgr = ". " + str(b) + " , " + str(g) +" , " + str(r)
        cv2.putText(img,color_bgr,(x,y),font,1,(155,225,130),2)
cv2.namedWindow(winname='res')
img = cv2.imread('pic.jpg')
cv2.setMouseCallback("res",mouse_event)
while True:
    cv2.imshow("res",img)
    if cv2.waitKey(1) == ord('q'):
        break
cv2.destroyAllWindows()

# COLOR PICKER PROJECT

In [98]:
def cross(x):
    pass

img = np.zeros((300,512,3),np.uint8)
cv2.namedWindow("Color picker")

s1 = "0:OFF\n1:ON"
cv2.createTrackbar(s1,"Color picker",0,1,cross)

cv2.createTrackbar("R","Color picker",0,255,cross)
cv2.createTrackbar("G","Color picker",0,255,cross)
cv2.createTrackbar("B","Color picker",0,255,cross)

while True:
    cv2.imshow("Color picker",img)
    if cv2.waitKey(1) == ord('q'):
        break

    s = cv2.getTrackbarPos(s1,"Color picker")
    r = cv2.getTrackbarPos("R","Color picker")
    g = cv2.getTrackbarPos("G","Color picker")
    b = cv2.getTrackbarPos("B","Color picker")

    if s==0:
        img[:] = 0
    else:
        img[:] = [b,g,r]

cv2.destroyAllWindows()

## merge and split

In [79]:
img = cv2.imread('./pic.jpg')
print('shape = ', img.shape)
print("no. of pixels = ", img.size)
print("datatype = ",img.dtype)
print("image type = ",type(img))

b,g,r = cv2.split(img)

cv2.imshow("blue",b)
cv2.imshow("green",g)
cv2.imshow("red",r)
cv2.imshow("image",img)

mr1 = cv2.merge((r,g,b))
cv2.imshow("rgb",mr1)

cv2.waitKey()
cv2.destroyAllWindows()

shape =  (694, 540, 3)
no. of pixels =  1124280
datatype =  uint8
image type =  <class 'numpy.ndarray'>


# Region of Interest

In [ ]:
img = cv2.imread("pic.jpg")
print(img.shape)
# (115,43)                      (398 ,380)

roi = img[45:380,115:400]      # (y1:y2,x1:x2)
# dy = 335 , dx = 285
img[24:380,401:500] = roi

cv2.imshow("image",img)
cv2.waitKey()
cv2.destroyAllWindows()